import type { Category, Product } from './types';

export const WHATSAPP_NUMBER = '233540645292';

export const categories: Category[] = [
  'Food Packs',
  'Paper Bags',
  'Plastic Bags',
  'Fabric Bags',
  'Bottles & Jars',
  'Disposable Plates',
  'Cups & Straws',
  'Custom Packaging',
  'Luxury Bags',
  'Event Supplies',
  'Bulk Bundles',
];

export const categoryImages: Record<Category, string> = {
  'Food Packs': '/images/food-packaging.png',
  'Paper Bags': '/images/retail-paper-bags-generated.png',
  'Plastic Bags': '/images/retail-plastic-bags-generated.png',
  'Fabric Bags': '/images/retail-fabric-bags-generated.png',
  'Bottles & Jars': '/images/honey-jars.png',
  'Disposable Plates': '/images/disposable-plates.png',
  'Cups & Straws': '/images/IMG_0505.jpeg',
  'Custom Packaging': '/images/luxury-bags.png',
  'Luxury Bags': '/images/luxury-bags.png',
  'Event Supplies': '/images/unboxing-showcase.png',
  'Bulk Bundles': '/images/plastic-packaging.png',
};

export const defaultProducts: Product[] = [
  {
    id: 'kraft-takeaway-boxes',
    title: 'Kraft Takeaway Food Boxes',
    slug: 'kraft-takeaway-food-boxes',
    description:
      'Strong kraft food boxes for restaurants, food vendors, caterers, bakeries, and delivery kitchens. Clean presentation with dependable structure for daily takeaway orders.',
    category: 'Food Packs',
    images: ['/images/food-packaging.png', '/images/IMG_0502.jpeg', '/images/IMG_0504.jpeg'],
    basePrice: 85,
    sizes: [
      { label: 'Small pack of 50', price: 85 },
      { label: 'Medium pack of 50', price: 110 },
      { label: 'Large pack of 50', price: 145 },
      { label: 'Bulk carton', price: 620 },
    ],
    colors: ['Kraft', 'White', 'Black lid option'],
    available: true,
    featured: true,
    badge: 'Best seller',
    rating: 4.9,
    reviews: 74,
    turnaround: 'Same day pickup when available',
  },
  {
    id: 'clear-plastic-food-containers',
    title: 'Clear Plastic Food Containers',
    slug: 'clear-plastic-food-containers',
    description:
      'Clear hinged containers for salads, pastries, rice dishes, fruit, snacks, and chilled takeaway meals. Great for shops that need customers to see the product clearly.',
    category: 'Food Packs',
    images: ['/images/plastic-packaging.png', '/images/plasticfoodpack.jpeg', '/images/IMG_0507.jpeg'],
    basePrice: 70,
    sizes: [
      { label: 'Small pack of 50', price: 70 },
      { label: 'Medium pack of 50', price: 95 },
      { label: 'Large pack of 50', price: 125 },
      { label: 'Bulk carton', price: 520 },
    ],
    colors: ['Clear', 'Black base', 'White base'],
    available: true,
    featured: true,
    badge: 'Food safe',
    rating: 4.8,
    reviews: 58,
    turnaround: 'Same day pickup when available',
  },
  {
    id: 'twisted-handle-paper-bags',
    title: 'Paper Retail Shopping Bags',
    slug: 'paper-retail-shopping-bags',
    description:
      'Clean kraft and white paper retail bags with twisted handles for boutiques, bakeries, gift shops, pharmacies, events, and food brands. Available plain or ready for branded stickers.',
    category: 'Paper Bags',
    images: ['/images/retail-paper-bags-generated.png', '/images/paper-bags.png', '/images/paperbags.jpeg', '/images/IMG_0499.jpeg'],
    basePrice: 95,
    sizes: [
      { label: 'Small bundle of 50', price: 95 },
      { label: 'Medium bundle of 50', price: 135 },
      { label: 'Large bundle of 50', price: 180 },
      { label: 'Bulk carton of 500', price: 780 },
    ],
    colors: ['Kraft brown', 'White', 'Black', 'Custom sticker ready'],
    available: true,
    featured: true,
    badge: 'Retail ready',
    rating: 4.9,
    reviews: 46,
    turnaround: '1-2 working days',
  },
  {
    id: 'die-cut-plastic-retail-bags',
    title: 'Die-Cut Plastic Retail Bags',
    slug: 'die-cut-plastic-retail-bags',
    description:
      'Lightweight die-cut plastic carrier bags with punched handles for retail shops, cosmetics, pharmacies, food vendors, trade fairs, and everyday customer packaging.',
    category: 'Plastic Bags',
    images: ['/images/retail-plastic-bags-generated.png', '/images/die-cut-plastic-bags-generated.png'],
    basePrice: 75,
    sizes: [
      { label: 'Small pack of 100', price: 75 },
      { label: 'Medium pack of 100', price: 110 },
      { label: 'Large pack of 100', price: 155 },
      { label: 'Bulk carton of 1000', price: 980 },
    ],
    colors: ['White', 'Clear frosted', 'Green', 'Black', 'Mixed colors'],
    available: true,
    featured: true,
    badge: 'Lightweight',
    rating: 4.8,
    reviews: 39,
    turnaround: 'Same day pickup when available',
  },
  {
    id: 'non-woven-fabric-retail-bags',
    title: 'Non-Woven Fabric Retail Bags',
    slug: 'non-woven-fabric-retail-bags',
    description:
      'Reusable fabric retail bags for boutiques, conferences, giveaways, packaging sets, and premium customer handouts. Stronger than regular plastic and suitable for repeat use.',
    category: 'Fabric Bags',
    images: ['/images/non-woven-fabric-bags-generated.png'],
    basePrice: 145,
    sizes: [
      { label: 'Small bundle of 25', price: 145 },
      { label: 'Medium bundle of 25', price: 210 },
      { label: 'Large bundle of 25', price: 290 },
      { label: 'Bulk order of 250', price: 2450 },
    ],
    colors: ['Red', 'White', 'Black', 'Navy', 'Custom color on request'],
    available: true,
    featured: true,
    badge: 'Reusable',
    rating: 4.9,
    reviews: 28,
    turnaround: '2-5 working days',
  },
  {
    id: 'organza-drawstring-gift-pouches',
    title: 'Organza Drawstring Gift Pouches',
    slug: 'organza-drawstring-gift-pouches',
    description:
      'Soft drawstring fabric pouches for jewelry, party favors, beads, cosmetics, soap, small gifts, and event packaging. Lightweight presentation for small premium items.',
    category: 'Fabric Bags',
    images: ['/images/organza-pouches-generated.png'],
    basePrice: 60,
    sizes: [
      { label: 'Small pack of 50', price: 60 },
      { label: 'Medium pack of 50', price: 90 },
      { label: 'Large pack of 50', price: 130 },
      { label: 'Bulk pack of 500', price: 720 },
    ],
    colors: ['White', 'Gold', 'Silver', 'Pink', 'Light blue'],
    available: true,
    featured: false,
    badge: 'Gift pouch',
    rating: 4.7,
    reviews: 21,
    turnaround: '1-3 working days',
  },
  {
    id: 'luxury-gift-bags',
    title: 'Luxury Gift & Boutique Bags',
    slug: 'luxury-gift-boutique-bags',
    description:
      'Premium gift bags for boutiques, bridal packages, event favors, corporate gifting, and upscale product presentation.',
    category: 'Luxury Bags',
    images: ['/images/luxury-bags.png'],
    basePrice: 160,
    sizes: [
      { label: 'Small bundle of 25', price: 160 },
      { label: 'Medium bundle of 25', price: 230 },
      { label: 'Large bundle of 25', price: 320 },
    ],
    colors: ['White', 'Black', 'Navy', 'Pastel mix'],
    available: true,
    featured: true,
    badge: 'Premium',
    rating: 4.8,
    reviews: 34,
    turnaround: '2-4 working days',
  },
  {
    id: 'honey-jars-with-lids',
    title: 'Honey Jars with Lids',
    slug: 'honey-jars-with-lids',
    description:
      'Clean jars for honey, spices, sauces, body butter, cosmetics, and small batch products. Suitable for startups and refill orders.',
    category: 'Bottles & Jars',
    images: ['/images/honey-jars.png', '/images/smalltransbottles.jpeg', '/images/IMG_0508.jpeg'],
    basePrice: 120,
    sizes: [
      { label: '100ml pack of 24', price: 120 },
      { label: '250ml pack of 24', price: 190 },
      { label: '500ml pack of 24', price: 290 },
      { label: 'Bulk carton', price: 860 },
    ],
    colors: ['Clear', 'Amber', 'White lid', 'Black lid'],
    available: true,
    featured: false,
    rating: 4.7,
    reviews: 29,
    turnaround: '1-3 working days',
  },
  {
    id: 'disposable-plates-party-pack',
    title: 'Disposable Plates Party Pack',
    slug: 'disposable-plates-party-pack',
    description:
      'Disposable plates for weddings, funerals, birthdays, school programs, church events, corporate meetings, and catering teams.',
    category: 'Disposable Plates',
    images: ['/images/disposable-plates.png', '/images/IMG_0494.jpeg', '/images/IMG_0495.jpeg'],
    basePrice: 55,
    sizes: [
      { label: 'Small pack', price: 55 },
      { label: 'Medium pack', price: 85 },
      { label: 'Large pack', price: 120 },
      { label: 'Event carton', price: 450 },
    ],
    colors: ['White', 'Clear', 'Gold rim option'],
    available: true,
    featured: false,
    rating: 4.6,
    reviews: 37,
    turnaround: 'Same day pickup when available',
  },
  {
    id: 'custom-branded-sticker-pack',
    title: 'Custom Branded Sticker Pack',
    slug: 'custom-branded-sticker-pack',
    description:
      'Logo stickers for bags, jars, bottles, boxes, and event favors. A simple way to turn plain packaging into branded packaging.',
    category: 'Custom Packaging',
    images: ['/images/custom-sticker-sheets-generated.png'],
    basePrice: 140,
    sizes: [
      { label: '100 stickers', price: 140 },
      { label: '250 stickers', price: 260 },
      { label: '500 stickers', price: 450 },
      { label: '1000 stickers', price: 780 },
    ],
    colors: ['Matte', 'Gloss', 'Transparent', 'White base'],
    available: true,
    featured: true,
    badge: 'Branding',
    rating: 4.9,
    reviews: 51,
    turnaround: '3-5 working days',
  },
  {
    id: 'event-packaging-bundle',
    title: 'Event Packaging Bundle',
    slug: 'event-packaging-bundle',
    description:
      'A coordinated mix of food packs, plates, cups, bags, and napkins for weddings, funerals, parties, church events, and corporate programs.',
    category: 'Event Supplies',
    images: ['/images/unboxing-showcase.png', '/images/disposable-plates.png', '/images/food-packaging.png'],
    basePrice: 350,
    sizes: [
      { label: '50 guests', price: 350 },
      { label: '100 guests', price: 650 },
      { label: '200 guests', price: 1180 },
      { label: 'Custom bulk quote', price: 0 },
    ],
    colors: ['White', 'Kraft', 'Clear', 'Mixed'],
    available: true,
    featured: true,
    badge: 'Events',
    rating: 4.8,
    reviews: 42,
    turnaround: '2-5 working days',
  },
  {
    id: 'restaurant-supply-bundle',
    title: 'Restaurant Supply Bundle',
    slug: 'restaurant-supply-bundle',
    description:
      'Bulk packaging bundle for restaurants, takeaway spots, bakeries, and delivery kitchens that need reliable weekly supply.',
    category: 'Bulk Bundles',
    images: ['/images/plastic-packaging.png', '/images/food-packaging.png', '/images/paper-bags.png'],
    basePrice: 980,
    sizes: [
      { label: 'Starter weekly bundle', price: 980 },
      { label: 'Growth bundle', price: 1680 },
      { label: 'High-volume bundle', price: 2850 },
    ],
    colors: ['Kraft', 'White', 'Clear', 'Mixed'],
    available: true,
    featured: false,
    badge: 'Bulk',
    rating: 4.9,
    reviews: 23,
    turnaround: '2-4 working days',
  },
];

export const formatPrice = (amount: number) => {
  if (amount === 0) return 'Request quote';
  return new Intl.NumberFormat('en-GH', {
    style: 'currency',
    currency: 'GHS',
    maximumFractionDigits: 0,
  }).format(amount);
};

export const productStorageKey = 'ghanapack.products.v3';
export const inquiryStorageKey = 'ghanapack.inquiries.v1';
